Preper For Shooting
primo4586/RobotCode2024 pull request #15
Opened 2024-01-20 13:50 UTC by DrorMargalit17

adding interpoilation to ShooterArm, creating Paralall command group (prepertion for shooting) and StartFeeder command if ShooterArm and Shooter ready

2024-01-20 14:34 UTC, ori-coval requested changes

2024-01-20 14:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
> +    this.addRequirements(shooterSubsysem);
shooter isnt a requirements feeder is

2024-01-20 14:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
change the name to feed to shooter

2024-01-20 14:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
> +  public StartFeeder(double speed) {
dont get a speed use a constant

2024-01-20 14:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/PreperForShootting.java
this is not how you write prepare

2024-01-20 14:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/PreperForShootting.java
> +    this.addRequirements(shooterSubsysem);;
shooter arm is also a requirment

2024-01-20 14:39 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/PreperForShootting.java
> +    this.addRequirements(shooterSubsysem);;
fixed

2024-01-20 14:40 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/PreperForShootting.java
fixed

2024-01-20 14:42 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
> +    this.addRequirements(shooterSubsysem);
fixed

2024-01-20 14:43 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
fixed

2024-01-20 14:45 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/feederCommands/StartFeeder.java
> +  public StartFeeder(double speed) {
fixed

2024-01-21 13:34 UTC, ori-coval requested changes

2024-01-21 13:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/feederCommands/FeedToShooter.java
> +    this.addRequirements(feederSubsystem, shooterArmSubsystem, shooterSubsysem);
only feederSubsystem is a requirement

2024-01-21 13:34 UTC, ori-coval commented on src/main/java/frc/robot/Constants.java
> +    public static final int speed = 20;
`FeederShootSpeed`

2024-01-21 13:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/PrepareForShooting.java
> +  public PrepareForShooting(double degree) {
remove `double degree` from both places

2024-01-21 13:34 UTC, ori-coval commented on src/main/java/frc/robot/commands/PrepareForShooting.java
> +    this.addRequirements(shooterSubsysem, shooterArmSubsystem);
no addRequirements for command Groups

2024-01-22 06:22 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/PrepareForShooting.java
> +    this.addRequirements(shooterSubsysem, shooterArmSubsystem);
fixed

2024-01-22 06:30 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/PrepareForShooting.java
> +  public PrepareForShooting(double degree) {
fixed

2024-01-22 06:51 UTC, DrorMargalit17 commented on src/main/java/frc/robot/Constants.java
> +    public static final int speed = 20;
fixed

2024-01-22 06:51 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/feederCommands/FeedToShooter.java
> +    this.addRequirements(feederSubsystem, shooterArmSubsystem, shooterSubsysem);
fixed

2024-01-22 13:15 UTC, ori-coval approved these changes

2024-01-22 13:15 UTC, merged