Punk 2.0
primo4586/RobotCode2024 pull request #18
Opened 2024-03-02 00:18 UTC by chenPerach

@ori-coval - next time you ask for a CR at least create a PR for me to go through

2024-03-02 16:41 UTC, ori-coval requested changes
Add ZeroShooterArm.

2024-03-02 16:41 UTC, ori-coval commented on src/main/java/frc/robot/basicCommands/SwerveCommands/TeleopAlignToSpeaker.java
> +  TakeFeedSubsystem feeder = TakeFeedSubsystem.getInstance();
Why????

2024-03-03 05:47 UTC, chenPerach reviewed
very good overall.
There are mostly documentation changes which I want you to implement.
grape🍇 - https://youtu.be/xOKBM16UFE4

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/Constants.java
> +    public static final String CAN_BUS_NAME = "canBus";
I think it might be Important to change this to "canivor can-bus" or something similar.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/FieldConstants.java
> +        new Pose2d(0.0, fieldWidth - Units.inchesToMeters(104.0), new Rotation2d());
hmm, maybe you can add a function called `applyAllianceTranslation` which will apply the `AllianceFlipUtils::apply` logic

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/basicCommands/ClimbCommands/ClimbSetSpeed.java
> +  }
where is finished?

is `isFinished` initialized to false by default?

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/basicCommands/SwerveCommands/AlignToAngle.java
> +    swerve.drive(new Translation2d(),0,true,false);
what the fuck does `0,true,false` mean?

Is this command incomplete?

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/basicCommands/ShooterArmCommands/ShooterArmMoveToAngle.java
> +  public ShooterArmMoveToAngle(double angle) {
Document what this function expects to get 
And don't just say 
> @param angle is the expected angle of the subsystem

say something more descriptive like what are the expected units of this angle (degrees, radians or encoder ticks?)
this should be at `moveArmTo` function also.

These documentation changes will help the next rashatz in your position understand how to write code and your line of thought. so adding them is worth it.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/basicCommands/ShooterCommands/ShooterSetSpeed.java
> +    shooter.setShooterSpeed(speed);
In my opinion, subsystems like these which are expected to have 2 or more ways of setting the speed (Percentage, Velocity, Voltage etc...) you are expected to be more explicit in the function name.

again this will help the next developer understand what you are trying to achieve.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/basicCommands/SwerveCommands/SwerveSetSpeed.java
> +  public SwerveSetSpeed(double translation, double strafe, double rotation, boolean fieldRelative, boolean isOpenLoop) {
God choose a better name then `setSpeed`, this function clearly does more

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java
> +    }
Again, think about it you are getting the velocity (angular, measured in ticks, radians or degrees...) 
This is a small but meaningful change.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java
> +    }
maybe you should create a more generic form of this function
```Java
    public boolean checkIfShooterAtVelocity(double targetVelocity, double acceptableError) {
        return (Math.abs(getUpShooterVelocity() - targetVelocity) < acceptableError)
                && (Math.abs(getDownShooterVelocity() - targetVelocity) < acceptableError);
    }
```
and then use function overloading to create a simpler version:
```Java
    public boolean checkIfShooterAtVelocity() {
        return checkIfShooterAtVelocity(targetVelocity, shooterConstants.MAX_ERROR);
    }
```

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java
> +    public double speakerInterpolate() {
Looks good, just document that this function returns the expected velocity of the shooter.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java
> +        TalonFXConfiguration downConfigs = new TalonFXConfiguration();
Fuck CTRE for not giving you a better way to statically create a configuration in the constants file.

2024-03-03 05:47 UTC, chenPerach commented on src/main/java/frc/robot/subsystems/shooterArm/ShooterArmSubsystem.java
> +  DigitalInput limitSwitch = new DigitalInput(shooterArmConstants.SWITCH_ID);
Can't stress enough how much this micro switch could not be trusted.

Make sure that if this switch breaks you still have some sort of fall back which makes sure the subsystem does not break.

2024-03-06 04:14 UTC, closed without merging