Shooter
primo4586/RobotCode2024 pull request #6
Opened 2024-01-17 22:43 UTC by DrorMargalit17

2024-01-18 06:57 UTC, ori-coval requested changes

2024-01-18 06:57 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsysem.java
> +  public ShooterSubsysem() {
constructor should be private

2024-01-18 06:57 UTC, ori-coval commented on src/main/java/frc/robot/commands/ShooterSetSpeedInterpolation.java
> +    this.addRequirements(shooterSubsystem, swerve);
swerve is not a requirement

2024-01-18 15:10 UTC, DrorMargalit17 commented on src/main/java/frc/robot/commands/ShooterSetSpeedInterpolation.java
> +    this.addRequirements(shooterSubsystem, swerve);
Done.

2024-01-18 15:10 UTC, DrorMargalit17 commented on src/main/java/frc/robot/subsystems/ShooterSubsysem.java
> +  public ShooterSubsysem() {
Done.

2024-01-19 08:12 UTC, ori-coval requested changes

2024-01-19 08:12 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/ShooterSubsysem.java
> +      return InterpolateUtil.interpolate(ShooterInterpolation, vision.DistanceFromTarget(swerve.getPose()));
why are you using `swerve.getPose()`  if you got a pose in the () `InterpolationValue(Pose2d pose2d){`

use the pose you got not the`swerve.getPose()`

2024-01-19 20:08 UTC, ori-coval commented on src/main/java/frc/robot/commands/ShooterSetSpeed.java
use instant command

2024-01-19 20:18 UTC, ori-coval approved these changes

2024-01-19 20:19 UTC, merged